[phases.setup]
nixPkgs = ["python313", "pip"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt --no-deps"
]

[start]
cmd = ". /opt/venv/bin/activate && python api/main.py"
