[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --no-cache-dir --no-deps -r requirements.txt"
]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
